CREATE DATABASE glove;
CREATE USER glove WITH ENCRYPTED PASSWORD 'gl0v3';

\c glove;

CREATE TABLE embeddings (
    key VARCHAR(1000) PRIMARY KEY,
    embedding JSONB
);

ALTER TABLE embeddings OWNER TO glove;
GRANT ALL PRIVILEGES ON DATABASE glove TO glove;
GRANT ALL PRIVILEGES ON embeddings TO glove;
